specfile_path: dist/rpm/rlc-cloud-repos.spec
downstream_package_name: rlc-cloud-repos
upstream_package_name: rlc_cloud_repos
upstream_ref: dev
create_pr: false

actions:
  post-upstream-clone:
    - make spec
  get-current-version:
    # This is some deep pcre voodoo to get the version from the file
    - grep -oP '__version__\s*=\s*[\p{QMark}]\K[^\p{QMark}]+' cloud-repos/rlc/cloud_repos/version.py
  create-archive:
    - make sdist
    - sh -c 'ls -1t dist/rlc_cloud_repos-*.tar.gz | head -n 1'
#   post-upstream-clone: "true" # prevent patch generation

jobs:
  - job: build
    trigger: pull_request
    targets:
      - centos-stream-9-x86_64

  - job: propose_downstream
    trigger: release
